/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { UniswapV2Pair, UniswapV2PairInterface } from "../UniswapV2Pair";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getReserves",
    outputs: [
      {
        internalType: "uint112",
        name: "reserve0",
        type: "uint112",
      },
      {
        internalType: "uint112",
        name: "reserve1",
        type: "uint112",
      },
      {
        internalType: "uint32",
        name: "blockTimestampLast",
        type: "uint32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class UniswapV2Pair__factory {
  static readonly abi = _abi;
  static createInterface(): UniswapV2PairInterface {
    return new Interface(_abi) as UniswapV2PairInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): UniswapV2Pair {
    return new Contract(address, _abi, runner) as unknown as UniswapV2Pair;
  }
}
